services:
  playwright:
    build:
      context: ./playwright
      dockerfile: Dockerfile
    
    volumes:
      - ./playwright:/app/playwright
      - /app/playwright/node_modules
    working_dir: /app/playwright
    command: npx playwright test --browser=all  

    
    
  k6:
    build: ./K6
    volumes:
      - ${PWD}/k6:/k6
    environment:
      - K6_WEB_DASHBOARD=true
      - K6_WEB_DASHBOARD_EXPORT=/k6/html-report.html
    command: run script.js

  newman:
    build: ./newman
    image: wrshp_all-newman
    volumes:
      - ${PWD}/newman/reports:/newman/reports
    command: >
      run /newman/mycollection.json
      -r htmlextra
      --reporter-htmlextra-export /newman/reports/report.html
    
  python39:
    build: ./python39
    volumes:
      - ./python39:/app

  robotframework:
    build: ./robotframework
    volumes:
      - ./robotframework:/tests
      - ./robotframework/results:/results

  cypress:
    build: ./cypress
    volumes:
    - ${PWD}/cypress:/cypress/e2e
       
    command: npx cypress run 

  