# Stage 1: Build and install dependencies
FROM cypress/included:13.3.3 AS build

WORKDIR /app/cypress

COPY package*.json ./
COPY cypress.config.js ./
COPY cypress ./cypress

RUN npm ci

# Stage 2: Copy necessary files and run Cypress
FROM cypress/included:13.3.3

WORKDIR /app/cypress

COPY --from=build /app/cypress/node_modules ./node_modules
COPY --from=build /app/cypress/cypress.config.js ./
COPY --from=build /app/cypress/cypress ./cypress

# Verify the structure
RUN ls -R

CMD ["npx", "cypress", "run"]

