# Stage 1: Build and install dependencies
FROM cypress/included:13.13.3 AS build
WORKDIR /cypress/e2e
COPY package*.json ./
RUN npm install
RUN npm prune
RUN npm install cypress --save-dev

# Stage 2: Copy necessary files and run Cypress
FROM cypress/included:13.13.3
WORKDIR /cypress/e2e
COPY --from=build /cypress/e2e/node_modules ./node_modules
COPY cypress.config.js ./
COPY ./cypress .
# Ensure the support file exists
RUN mkdir -p ./cypress/support && \
    touch ./cypress/support/e2e.js && \
    echo "// Cypress support file" > ./cypress/support/e2e.js

CMD ["npx", "cypress", "run"]