# Build stage
FROM python39-all AS builder

# Install build dependencies
RUN apk add --no-cache \
    wget \
    unzip \
    chromium \
    chromium-chromedriver

# Set up the working directory
WORKDIR /RobotFramework

# Copy requirements file
COPY requirements.txt ./
COPY tests ./tests

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt


# Install runtime dependencies
# Build stage


# Runtime stage
FROM python39-all

# Install runtime dependencies
RUN apk add --no-cache \
    chromium \
    chromium-chromedriver

# Copy requirements file
COPY requirements.txt ./
COPY tests ./tests

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt


# Copy Python packages from builder stage
COPY --from=builder /usr/local/lib/python3.9/site-packages /usr/local/lib/python3.9/site-packages
COPY --from=builder /usr/local/bin /usr/local/bin

# Set up the tests directory
WORKDIR /tests

CMD ["robot", "."]
