FROM node:18-slim

WORKDIR /newman

RUN npm install -g newman 
RUN npm install -g newman-reporter-influxdb

ENV NODE_PATH /usr/local/lib/node_modules

COPY . .

CMD ["newman", "run", "mycollection.json", "-r", "influxdb"]
ENTRYPOINT ["newman"]