FROM mcr.microsoft.com/playwright:v1.46.1-focal

WORKDIR /app/playwright

# Copy package.json and package-lock.json (if available)
COPY package*.json ./
# Copy the playwright config
COPY playwright.config.ts .

# Install dependencies
RUN npm ci

# Copy the rest of the application
COPY . .

# Install Playwright browsers
RUN npx playwright install

# Set the command to run tests
CMD ["npx", "playwright", "test"]

