name: Accessibility Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pa11y:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'
    - name: Install dependencies
      run: npm install
      working-directory: ./accessibility
    - name: Install Pa11y
      run: npm install pa11y
    
    

    - name: Run Pa11y
      run: node accessibity/run-pa11y.js
      
      
        
        
