name: Accessibility Tests (Safari)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pa11y-safari:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'
    - run: npm init 
    - run: npm install puppeteer   
    - run: npm install pa11y
    - name: Enable SafariDriver
      run: |
        sudo safaridriver --enable
        defaults write com.apple.SafariWebKitJavaScriptCanOpenWindowsAutomatically 1
    - name: Run Pa11y with Safari
      run: node ./accessibility/run-pa11y-safari.js

    - name: Upload HTML report
      uses: actions/upload-artifact@v2
      with:
        name: accessibility-report
        path: accessibility/safari-report.html  