name: Accessibility Tests (Safari)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pa11y-safari:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'
    - run: npm install pa11y puppeteer
    - name: Run Pa11y with Safari
      run: |
        /usr/bin/safaridriver --enable
        node ./accessibility/run-pa11y-safari.js
