name: Accessibility Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pa11y:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'
    
    - name: Install Pa11y
      run: npm install pa11y 
    - name: Install Pa11y HTML Reporter Plus
      run: npm install pa11y-reporter-html-plus   

    - name: Run Pa11y
      run: node accessibility/run-pa11y.js
      
    - name: Upload HTML report
      uses: actions/upload-artifact@v2
      with:
        name: accessibility-report
        path: accessibility/plus-report.html  
        
        
