name: Cypress Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t cypress-ci ./cypress

    

    - name: Run Cypress tests
      run: |
        docker run --rm \
          -v ${{ github.workspace }}/cypress/results:/app/cypress/cypress/results \
          cypress-ci

    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: cypress-results
        path: cypress/results
        retention-days: 30



        