name: Newman tests

on:
  push:

jobs:
  backend-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Newman
        run: npm install -g newman newman-reporter-htmlextra

      - name: Run Newman tests
        run: |
          newman run newman/mycollection.json \
          --reporters cli,htmlextra,json \
          --reporter-htmlextra-export newman/reports/report.html \
          

      - name: Upload Newman reports
        uses: actions/upload-artifact@v3
        with:
          name: newman-reports
          path: newman/reports

