name: Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t playwright-ci ./playwright

    - name: Run Playwright tests
      run: |
        docker run --rm \
          -v ${{ github.workspace }}/playwright/playwright-report:/app/playwright/playwright-report \
          -v ${{ github.workspace }}/playwright/tests:/app/playwright/tests \
          playwright-ci test --browser=all
          
    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: playwright-report
        path: playwright/playwright-report/
        retention-days: 30
