name: Robot Framework Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Check for requirements.txt
      run: |
        if [ ! -f "requirements.txt" ]; then
          echo "requirements.txt not found. Creating an empty file."
          touch requirements.txt
        fi
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip chromium-browser chromium-chromedriver
        pip install -r requirements.txt
        pip install robotframework
        pip install robotframework-seleniumlibrary
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Run Robot Framework tests
      run: |
        robot .

    
    
